package com.example.expensetracker.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

// Custom Modern Palette
val Primary = Color(0xFF6750A4)
val OnPrimary = Color(0xFFFFFFFF)
val PrimaryContainer = Color(0xFFEADDFF)
val OnPrimaryContainer = Color(0xFF21005D)

val Secondary = Color(0xFF625B71)
val OnSecondary = Color(0xFFFFFFFF)
val SecondaryContainer = Color(0xFFE8DEF8)
val OnSecondaryContainer = Color(0xFF1D192B)

val Tertiary = Color(0xFF7D5260)
val OnTertiary = Color(0xFFFFFFFF)
val TertiaryContainer = Color(0xFFFFD8E4)
val OnTertiaryContainer = Color(0xFF31111D)

val Error = Color(0xFFB3261E)
val OnError = Color(0xFFFFFFFF)
val ErrorContainer = Color(0xFFF9DEDC)
val OnErrorContainer = Color(0xFF410E0B)

val Background = Color(0xFFFFFBFE)
val OnBackground = Color(0xFF1C1B1F)
val Surface = Color(0xFFFFFBFE)
val OnSurface = Color(0xFF1C1B1F)
val SurfaceVariant = Color(0xFFE7E0EC)
val OnSurfaceVariant = Color(0xFF49454F)
val Outline = Color(0xFF79747E)

// Dark Theme Colors
val PrimaryDark = Color(0xFFD0BCFF)
val OnPrimaryDark = Color(0xFF381E72)
val PrimaryContainerDark = Color(0xFF4F378B)
val OnPrimaryContainerDark = Color(0xFFEADDFF)

val SecondaryDark = Color(0xFFCCC2DC)
val OnSecondaryDark = Color(0xFF332D41)
val SecondaryContainerDark = Color(0xFF4A4458)
val OnSecondaryContainerDark = Color(0xFFE8DEF8)

val TertiaryDark = Color(0xFFEFB8C8)
val OnTertiaryDark = Color(0xFF492532)
val TertiaryContainerDark = Color(0xFF633B48)
val OnTertiaryContainerDark = Color(0xFFFFD8E4)

val ErrorDark = Color(0xFFF2B8B5)
val OnErrorDark = Color(0xFF601410)
val ErrorContainerDark = Color(0xFF8C1D18)
val OnErrorContainerDark = Color(0xFFF9DEDC)

val BackgroundDark = Color(0xFF1C1B1F)
val OnBackgroundDark = Color(0xFFE6E1E5)
val SurfaceDark = Color(0xFF1C1B1F)
val OnSurfaceDark = Color(0xFFE6E1E5)
val SurfaceVariantDark = Color(0xFF49454F)
val OnSurfaceVariantDark = Color(0xFFCAC4D0)
val OutlineDark = Color(0xFF938F99)

// ---------------- MD3 Extra Themes (Redesigned) ----------------

// 1. Sakura Pink (樱花粉)
val PrimaryPink = Color(0xFF9E3D61)
val OnPrimaryPink = Color(0xFFFFFFFF)
val PrimaryContainerPink = Color(0xFFFFD9E2)
val OnPrimaryContainerPink = Color(0xFF3E001D)
val SecondaryPink = Color(0xFF75565F)
val OnSecondaryPink = Color(0xFFFFFFFF)
val SecondaryContainerPink = Color(0xFFFFD9E2)
val OnSecondaryContainerPink = Color(0xFF2B151C)
val TertiaryPink = Color(0xFF7C5635)
val OnTertiaryPink = Color(0xFFFFFFFF)
val TertiaryContainerPink = Color(0xFFFFDCC1)
val OnTertiaryContainerPink = Color(0xFF2E1500)
val ErrorPink = Color(0xFFBA1A1A)
val OnErrorPink = Color(0xFFFFFFFF)
val ErrorContainerPink = Color(0xFFFFDAD6)
val OnErrorContainerPink = Color(0xFF410002)

val PrimaryDarkPink = Color(0xFFFFB0C8)
val OnPrimaryDarkPink = Color(0xFF610833)
val PrimaryContainerDarkPink = Color(0xFF7F254A)
val OnPrimaryContainerDarkPink = Color(0xFFFFD9E2)
val SecondaryDarkPink = Color(0xFFE5BDC6)
val OnSecondaryDarkPink = Color(0xFF432931)
val SecondaryContainerDarkPink = Color(0xFF5C3F47)
val OnSecondaryContainerDarkPink = Color(0xFFFFD9E2)
val TertiaryDarkPink = Color(0xFFEFBD94)
val OnTertiaryDarkPink = Color(0xFF48290B)
val TertiaryContainerDarkPink = Color(0xFF623F20)
val OnTertiaryContainerDarkPink = Color(0xFFFFDCC1)
val ErrorDarkPink = Color(0xFFFFB4AB)
val OnErrorDarkPink = Color(0xFF690005)
val ErrorContainerDarkPink = Color(0xFF93000A)
val OnErrorContainerDarkPink = Color(0xFFFFDAD6)

// 2. Gulf Blue (海湾蓝)
val PrimaryGulf = Color(0xFF006399)
val OnPrimaryGulf = Color(0xFFFFFFFF)
val PrimaryContainerGulf = Color(0xFFCDE5FF)
val OnPrimaryContainerGulf = Color(0xFF001D32)
val SecondaryGulf = Color(0xFF51606F)
val OnSecondaryGulf = Color(0xFFFFFFFF)
val SecondaryContainerGulf = Color(0xFFD5E4F6)
val OnSecondaryContainerGulf = Color(0xFF0D1D2A)
val TertiaryGulf = Color(0xFF68587A)
val OnTertiaryGulf = Color(0xFFFFFFFF)
val TertiaryContainerGulf = Color(0xFFEFDBFF)
val OnTertiaryContainerGulf = Color(0xFF231533)
val ErrorGulf = Color(0xFFBA1A1A)
val OnErrorGulf = Color(0xFFFFFFFF)
val ErrorContainerGulf = Color(0xFFFFDAD6)
val OnErrorContainerGulf = Color(0xFF410002)

val PrimaryDarkGulf = Color(0xFF96CCFF)
val OnPrimaryDarkGulf = Color(0xFF003353)
val PrimaryContainerDarkGulf = Color(0xFF004A75)
val OnPrimaryContainerDarkGulf = Color(0xFFCDE5FF)
val SecondaryDarkGulf = Color(0xFFB9C8DA)
val OnSecondaryDarkGulf = Color(0xFF233240)
val SecondaryContainerDarkGulf = Color(0xFF394857)
val OnSecondaryContainerDarkGulf = Color(0xFFD5E4F6)
val TertiaryDarkGulf = Color(0xFFD2BFE6)
val OnTertiaryDarkGulf = Color(0xFF382A49)
val TertiaryContainerDarkGulf = Color(0xFF504061)
val OnTertiaryContainerDarkGulf = Color(0xFFEFDBFF)
val ErrorDarkGulf = Color(0xFFFFB4AB)
val OnErrorDarkGulf = Color(0xFF690005)
val ErrorContainerDarkGulf = Color(0xFF93000A)
val OnErrorContainerDarkGulf = Color(0xFFFFDAD6)

// 3. Field Green (原野绿)
val PrimaryField = Color(0xFF3A6939)
val OnPrimaryField = Color(0xFFFFFFFF)
val PrimaryContainerField = Color(0xFFBCEFB4)
val OnPrimaryContainerField = Color(0xFF002204)
val SecondaryField = Color(0xFF53634F)
val OnSecondaryField = Color(0xFFFFFFFF)
val SecondaryContainerField = Color(0xFFD6E8CE)
val OnSecondaryContainerField = Color(0xFF111F0F)
val TertiaryField = Color(0xFF38656A)
val OnTertiaryField = Color(0xFFFFFFFF)
val TertiaryContainerField = Color(0xFFBDEAF0)
val OnTertiaryContainerField = Color(0xFF002022)
val ErrorField = Color(0xFFBA1A1A)
val OnErrorField = Color(0xFFFFFFFF)
val ErrorContainerField = Color(0xFFFFDAD6)
val OnErrorContainerField = Color(0xFF410002)

val PrimaryDarkField = Color(0xFFA1D29A)
val OnPrimaryDarkField = Color(0xFF053910)
val PrimaryContainerDarkField = Color(0xFF215024)
val OnPrimaryContainerDarkField = Color(0xFFBCEFB4)
val SecondaryDarkField = Color(0xFFBACCB3)
val OnSecondaryDarkField = Color(0xFF263423)
val SecondaryContainerDarkField = Color(0xFF3C4B38)
val OnSecondaryContainerDarkField = Color(0xFFD6E8CE)
val TertiaryDarkField = Color(0xFFA1CED3)
val OnTertiaryDarkField = Color(0xFF00373C)
val TertiaryContainerDarkField = Color(0xFF1F4D52)
val OnTertiaryContainerDarkField = Color(0xFFBDEAF0)
val ErrorDarkField = Color(0xFFFFB4AB)
val OnErrorDarkField = Color(0xFF690005)
val ErrorContainerDarkField = Color(0xFF93000A)
val OnErrorContainerDarkField = Color(0xFFFFDAD6)

// 4. Autumn Yellow (秋黄)
val PrimaryAutumn = Color(0xFF755B00)
val OnPrimaryAutumn = Color(0xFFFFFFFF)
val PrimaryContainerAutumn = Color(0xFFFFDF92)
val OnPrimaryContainerAutumn = Color(0xFF241A00)
val SecondaryAutumn = Color(0xFF695D3F)
val OnSecondaryAutumn = Color(0xFFFFFFFF)
val SecondaryContainerAutumn = Color(0xFFF3E1BB)
val OnSecondaryContainerAutumn = Color(0xFF231B04)
val TertiaryAutumn = Color(0xFF496546)
val OnTertiaryAutumn = Color(0xFFFFFFFF)
val TertiaryContainerAutumn = Color(0xFFCBEBC4)
val OnTertiaryContainerAutumn = Color(0xFF072109)
val ErrorAutumn = Color(0xFFBA1A1A)
val OnErrorAutumn = Color(0xFFFFFFFF)
val ErrorContainerAutumn = Color(0xFFFFDAD6)
val OnErrorContainerAutumn = Color(0xFF410002)

val PrimaryDarkAutumn = Color(0xFFE9C349)
val OnPrimaryDarkAutumn = Color(0xFF3E2E00)
val PrimaryContainerDarkAutumn = Color(0xFF594400)
val OnPrimaryContainerDarkAutumn = Color(0xFFFFDF92)
val SecondaryDarkAutumn = Color(0xFFD6C5A0)
val OnSecondaryDarkAutumn = Color(0xFF392F15)
val SecondaryContainerDarkAutumn = Color(0xFF50452A)
val OnSecondaryContainerDarkAutumn = Color(0xFFF3E1BB)
val TertiaryDarkAutumn = Color(0xFFAFCFA9)
val OnTertiaryDarkAutumn = Color(0xFF1C361B)
val TertiaryContainerDarkAutumn = Color(0xFF324D30)
val OnTertiaryContainerDarkAutumn = Color(0xFFCBEBC4)
val ErrorDarkAutumn = Color(0xFFFFB4AB)
val OnErrorDarkAutumn = Color(0xFF690005)
val ErrorContainerDarkAutumn = Color(0xFF93000A)
val OnErrorContainerDarkAutumn = Color(0xFFFFDAD6)

// 5. Neutral Black (中性黑)
val PrimaryNeutral = Color(0xFF5E5E5E)
val OnPrimaryNeutral = Color(0xFFFFFFFF)
val PrimaryContainerNeutral = Color(0xFFE6E2E1)
val OnPrimaryContainerNeutral = Color(0xFF1B1B1B)
val SecondaryNeutral = Color(0xFF5F5E5E)
val OnSecondaryNeutral = Color(0xFFFFFFFF)
val SecondaryContainerNeutral = Color(0xFFE6E2E1)
val OnSecondaryContainerNeutral = Color(0xFF1C1B1B)
val TertiaryNeutral = Color(0xFF5E5E5E)
val OnTertiaryNeutral = Color(0xFFFFFFFF)
val TertiaryContainerNeutral = Color(0xFFE6E2E1)
val OnTertiaryContainerNeutral = Color(0xFF1B1B1B)
val ErrorNeutral = Color(0xFFBA1A1A)
val OnErrorNeutral = Color(0xFFFFFFFF)
val ErrorContainerNeutral = Color(0xFFFFDAD6)
val OnErrorContainerNeutral = Color(0xFF410002)

val PrimaryDarkNeutral = Color(0xFFC9C6C5)
val OnPrimaryDarkNeutral = Color(0xFF303030)
val PrimaryContainerDarkNeutral = Color(0xFF464646)
val OnPrimaryContainerDarkNeutral = Color(0xFFE6E2E1)
val SecondaryDarkNeutral = Color(0xFFC9C6C5)
val OnSecondaryDarkNeutral = Color(0xFF303030)
val SecondaryContainerDarkNeutral = Color(0xFF474747)
val OnSecondaryContainerDarkNeutral = Color(0xFFE6E2E1)
val TertiaryDarkNeutral = Color(0xFFC9C6C5)
val OnTertiaryDarkNeutral = Color(0xFF303030)
val TertiaryContainerDarkNeutral = Color(0xFF464646)
val OnTertiaryContainerDarkNeutral = Color(0xFFE6E2E1)
val ErrorDarkNeutral = Color(0xFFFFB4AB)
val OnErrorDarkNeutral = Color(0xFF690005)
val ErrorContainerDarkNeutral = Color(0xFF93000A)
val OnErrorContainerDarkNeutral = Color(0xFFFFDAD6)
